name: Vprofile CI/CD Workflow

on:
  push:
    branches: [ "main", "develop" ]

  pull_request: 
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Maven Build
        run: mvn install
  
  Testing:
    runs-on: ububuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run on maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle
      
